//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassOperation
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public GradeOperationType OperationType { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Class Class { get; set; }
    }
}
